### PR TITLE
Fix autoFill problem for new registration

### PR DESCRIPTION
**Pull request by mohalobaidi**

### CODE REVIEW

**Comment by mohalobaidi** [comment]
Fix autoFill problem for new registration

**Comment by ajmalali** [comment]
How were you able to test it?

**Comment by mohalobaidi** [comment]
I've already been using it in [Course Offering](https://chrome.google.com/webstore/detail/kfupm-course-offering/jajiinopiopggfikifkepeklkfpcbhnm). But you should test it before publishing it ofc.

**Comment by ajmalali** [comment]
So you tested it with the actual registration page with your extension? Btw, nice job on it! looks great.

**Comment by mohalobaidi** [comment]
Thx 💜. Yes it has been tested. But as I said, you should test it bc I myself don't trust my code 😅.

**Pull request merged**
